### ISSUE TITLE
3D Visor error: Failed to fetch while using sharepoint

### ISSUE THREAD

**Issue by dmitry-ivanov-mm** [diego-apellaniz/PowerBI3D#1]
Hi Diego,

First of all, thank you for sharing the component. I've downloaded one from food4rhino and getting the following error when trying to using a link to the sharepoint:

![image](https://github.com/user-attachments/assets/adb8dc13-61e0-4715-a1e6-04ebcbbab6c0)

Is there a way around it?

Thanks
Dmitry

**Comment by diego-apellaniz** [comment]
Hello Dmitry,

I'm sorry baout that. The sharepoint link has to be created as defined in the example Grasshopper file here (see Example files):
https://www.food4rhino.com/en/app/powerbi3d?lang=de

If it still does not work feel free to send me a private message/email with the link and we'll figure out the problem.

Best,
Diego
